//GST Treatment
export const GST_TREATMENT = {
    REGISTERED_BUSINESS_REGULAR: 1,
    REGISTERED_BUSINESS_COMPOSITION: 2,
    UNREGISTERED_BUSINESS: 3,
    CONSUMER: 4,
    OVERSEAS: 5,
    SPECIAL_ENOCONMIC_ZONE: 6,
    DEEMED_EXPORT: 7,
    TAX_DEDUCTOR: 8,
    SES_DEVELOPER: 9,
};  