"use client"
import Head from 'next/head';
import { useEffect, useContext } from "react";
import Image from 'next/image';
import Link from 'next/link';
import AllCustomerTable from '../../../components/allCustomerTable.js';
import FaCirclePlus from "../../../assets/icons/FaCirclePlus.svg";
import styles from '../../../styles/customers.module.scss';
import { NavExpandedState } from '../../../context/NavState.context';

export default function Customers() {
    const { navExpandedState } = useContext(NavExpandedState);
    return (<>
        <div className={styles.container}>
            <Head>
                <title>Groovy Invoice</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${navExpandedState ? styles.expanded : " "}`}>
                <div className="container-fluid">
                    <div className={`${styles.comapnyInvoiceHeadingWrapper} row`}>
                        <div className="col-6">
                            <h2 className={`${styles.title}`}>
                                All Customers
                            </h2>
                        </div>
                        <div className="col-6 d-flex justify-content-end">
                            <Link href={'/customers/add'}>
                                <button className="green align-content-center">
                                    <FaCirclePlus />
                                    Add Customer
                                </button>
                            </Link>
                        </div>
                    </div>
                    <div className='p-2'>
                        <AllCustomerTable />
                    </div>
                </div>
            </main>
        </div>
    </>)
}