import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import AllUserTable from "../../components/allUsersTable";
import FaCirclePlus from "../../assets/icons/faCirclePlus.svg";
import styles from '../../styles/user.module.scss';

export default function Customers({ navExpandedState }) {
    return (<>
        <div className={styles.container}>
            <Head>
                <title>Groovy Invoice</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${navExpandedState ? styles.expanded : " "}`}>
                <div className="container-fluid">
                    <div className={`${styles.comapnyInvoiceHeadingWrapper} row`}>
                        <div className="col-6">
                            <h2 className={`${styles.title}`}>
                                All Users
                            </h2>
                        </div>
                        <div className="col-6 d-flex justify-content-end">
                            <Link href={'/users/add'}>
                                <button className="green align-content-center">
                                    <FaCirclePlus />
                                    Add User
                                </button>
                            </Link>
                        </div>
                    </div>
                    <div className='p-2'>
                        <AllUserTable />
                    </div>
                </div>
            </main>
        </div>
    </>)
}