import { useState } from 'react';
import Head from 'next/head';
import RadioButton from '../components/radioButton';
import FaSkype from '../assets/icons/faSkype.svg';
import styles from "../styles/newCustomer.module.scss";

const NewCustomer = ({ navExpandedState }) => {
    const [customerTypeSelected, setcustomerTypeSelected] = useState();

    const handleBusinessChange = () => {
        setcustomerTypeSelected('business');
    };

    const handleIndividualChange = () => {
        setcustomerTypeSelected('individual');
    };
    return (
        <div>
            <Head>
                <title>Groovy Invoice - New Invoice</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${navExpandedState ? styles.expanded : " "}`}>
                <h2 className={`${styles.title}`}>
                    New Customer
                </h2>
                <div className="container-fluid">
                    <div className={`${styles.card} card`}>
                        <div className={`${styles.cardBody} card-body`}>
                            <h4 className={`${styles.cardTitle} card-title`}>Customer Details</h4>

                            <hr />

                            <div className={`${styles.companyCustomerTypeOptionWrapper} mb-2 mb-md-3 row`}>
                                <div className="col-12 col-md-2">
                                    <label className="">Customer Type</label>
                                </div>
                                <div className="col-12 col-md-6">
                                    <span className={`${styles.companyCustomerTypeSelectorMainWrapper}`}>
                                        <span className={`${styles.customerTypeBusinessRadioButtonWrapper} d-flex align-items-center`}>
                                            <RadioButton
                                                label="Business"
                                                value={customerTypeSelected === 'business'}
                                                onChange={handleBusinessChange}
                                            />
                                        </span>
                                        <span className={`${styles.customerTypeIndividualRadioButtonWrapper} d-flex align-items-center`}>
                                            <RadioButton
                                                label="Individual"
                                                value={customerTypeSelected === 'individual'}
                                                onChange={handleIndividualChange}
                                            />
                                        </span>
                                    </span>
                                </div>
                            </div>

                            <div className={`${styles.companyInvoiceNameWrapper} mb-2 mb-md-3 row`}>
                                <div className="col-12 col-md-2">
                                    <label className="">Primary Contact</label>
                                </div>
                                <div className="col-12 col-md-2">
                                    <select className={`${styles.companySalutationSelect} form-select`}>
                                        <option defaultValue>Salutation</option>
                                        <option value="ms">Ms.</option>
                                        <option value="mr">Mr.</option>
                                        <option value="mrs">Mrs.</option>
                                        <option value="dr">Dr.</option>
                                    </select>
                                </div>
                                <div className="col-12 col-md-2">
                                    <input type="text" className="form-control" id="companyInvoiceNewCustomerLastName" placeholder='Last Name' />
                                </div>
                                <div className="col-12 col-md-2">
                                    <input type="text" className={`${styles.companyInvoiceNewCustomerFirstName} form-control`} placeholder='First Name' />
                                </div>
                            </div>

                            <div className={`${styles.companyInvoiceComapnyNameWrapper} mb-2 mb-md-3 row`}>
                                <div className="col-12 col-md-2">
                                    <label className={`${styles.companyInvoiceComapnyNameLabel}`}>Comapny Name</label>
                                </div>
                                <div className="col-12 col-md-4">
                                    <input type="text" className="form-control" id="companyInvoiceNewCustomerComapnyName" placeholder='Company Name' />
                                </div>
                            </div>

                            <div className={`${styles.companyInvoiceComapnyDisplayNameWrapper} mb-2 mb-md-3 row`}>
                                <div className="col-12 col-md-2">
                                    <label className={`${styles.companyInvoiceComapnyDisplayNamelabel}`}>Customer Display Name*</label>
                                </div>
                                <div className="col-12 col-md-4">
                                    <select className={`${styles.companyInvoiceComapnyDisplaySelect} form-select`}>
                                        <option defaultValue>Customer Display Name</option>
                                        <option value="1">Option 1</option>
                                        <option value="2">Option 2</option>
                                        <option value="3">Option 3</option>
                                        <option value="4">Option 4</option>
                                    </select>
                                </div>
                            </div>

                            <div className={`${styles.companyInvoiceComapnyEmailWrapper} mb-2 mb-md-3 row`}>
                                <div className="col-12 col-md-2">
                                    <label className={`${styles.companyInvoiceComapnyEmailLabel}`}>Customer Email</label>
                                </div>
                                <div className="col-12 col-md-4">
                                    <input type="email" className="form-control" id="companyInvoiceComapnyEmail" placeholder='Company Email' />
                                </div>
                            </div>

                            <div className={`${styles.companyInvoiceComapnyPhone} mb-2 mb-md-3 row`}>
                                <div className="col-12 col-md-2">
                                    <label className={`${styles.companyInvoiceComapnyPhoneLabel}`}>Customer Phone</label>
                                </div>
                                <div className="col-12 col-md-2">
                                    <input type="text" className={`${styles.companyInvoiceComapnyWorkPhone} form-control`} placeholder='Work Phone' />
                                </div>
                                <div className="col-12 col-md-2">
                                    <input type="text" className={`${styles.companyInvoiceComapnyMobile} form-control`} placeholder='Mobile' />
                                </div>
                            </div>

                            <div className={`${styles.companyInvoiceComapnySkypeIDWrapper} mb-2 mb-md-3 row`}>
                                <div className="col-12 col-md-2">
                                    <label className={`${styles.companyInvoiceComapnySkypeIDLabel}`}>Skype Name/Number</label>
                                </div>
                                <div className="col-12 col-md-4">
                                    <div className="input-group">
                                        <span class="input-group-text"><FaSkype /></span>
                                        <input type="text" className="form-control" id="companyInvoiceComapnySkypeID" placeholder='Skype name/number' />
                                    </div>
                                </div>
                            </div>

                            <div className={`${styles.companyInvoiceDesignationWrapper} mb-2 mb-md-3row`}>
                                <div className="col-12 col-md-2">
                                    <label className={`${styles.companyInvoiceDesignationlabel}`}>Designation</label>
                                </div>
                                <div className="col-12 col-md-4">
                                    <input type="text" className="form-control" id="companyInvoiceDesignation" placeholder='Designation' />
                                </div>
                            </div>

                            <div className={`${styles.companyInvoiceDepartmentWrapper} mb-2 mb-md-3 row`}>
                                <div className="col-12 col-md-2">
                                    <label className={`${styles.companyInvoiceDepartmentLabel}`}>Department</label>
                                </div>
                                <div className="col-12 col-md-4">
                                    <input type="text" className="form-control" id="companyInvoiceDepartment" placeholder='Department' />
                                </div>
                            </div>

                            <div className={`${styles.companyInvoiceComapnyWebsiteWrapper} mb-2 mb-md-3 row`}>
                                <div className="col-12 col-md-2">
                                    <label className={`${styles.companyInvoiceComapnyWebsiteLabel}`}>Website</label>
                                </div>
                                <div className="col-12 col-md-4">
                                    <input type="text" className="form-control" id="companyInvoiceComapnyWebsiteW" placeholder='Website' />
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </main>
        </div>
    )
}

export default NewCustomer;