import Head from 'next/head';
import Image from 'next/image';
import styles from "../styles/newInvoice.module.scss"
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faSearch, faGear, faCalendar } from '@fortawesome/free-solid-svg-icons';
export default function Newinvoice({ navExpandedState }) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Groovy Invoice - New Invoice</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${navExpandedState ? styles.expanded : " "}`}>
                <h2 className={`${styles.title}`}>
                    New Invoice
                </h2>
                <div className="container-fluid">
                    <div className={`${styles.card} card`}>
                        <div className="card-body">
                            <h4 className={`${styles.cardTitle} card-title`}>Customer & Invoice Details</h4>
                            <hr />
                            <div className={`${styles.mainWrapper}`}>
                                <div className="row">
                                    <div className="col-md-4 ">
                                        <div className={`${styles.companyNameWrapper} form-group`}>
                                            <label htmlFor="companyName" className="form-label control-label">Comapny Name<span className={`${styles.green}`}>*</span></label>
                                            <div className="d-flex">
                                                <select className={`${styles.companyNameSelect} form-select`}>
                                                    <option defaultValue>Select Customer</option>
                                                    <option value="1">One</option>
                                                    <option value="2">Two</option>
                                                    <option value="3">Three</option>
                                                </select>
                                                <button className={`${styles.companySearchbutton} btn`}><i><FontAwesomeIcon icon={faSearch} /></i></button>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="col-sm-3">
                                        <div className={`${styles.companyInvoiceNumberWrapper} mb-3`}>
                                            <label htmlFor="companyInvoiceNumber" className="form-label">Invoice#<span className={`${styles.green}`}>*</span></label>
                                            <div className={`d-flex align-content-center`}>
                                                <input type="text" className="form-control" id="companyInvoiceNumber" aria-describedby="emailHelp" />
                                                <i><FontAwesomeIcon icon={faGear} /></i>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="col-sm-3">
                                        <div className={`${styles.companyOrderNumberWrapper} mb-3`}>
                                            <label htmlFor="companyOrderNumber" className="form-label">Order Number</label>
                                            <div className={`d-flex align-content-center`}>
                                                <input type="text" className="form-control" id="companyOrderNumber" aria-describedby="emailHelp" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="row">
                                    <div className="col-md-2">
                                        <div className={`${styles.companyInvoiceDateWrapper} mb-3`}>
                                            <label htmlFor="companyInvoiceDate" className="form-label">Invoice Date<span className={`${styles.green}`}>*</span></label>
                                            <div className={`d-flex align-content-center`}>
                                                <input type="text" className="form-control" id="companyInvoiceDate" aria-describedby="emailHelp" />
                                                <i><FontAwesomeIcon icon={faCalendar} /></i>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="col-md-2">
                                        <div className={`${styles.companyInvoicetermsWrapper} mb-3`}>
                                            <label htmlFor="companyInvoiceterms" className="form-label">Terms</label>
                                            <div className={`d-flex align-content-center`}>
                                                <input type="text" className="form-control" id="companyInvoiceterms" aria-describedby="emailHelp" />
                                            </div>
                                        </div>
                                    </div>
                                    <div className="col-md-2">
                                        <div className={`${styles.companyInvoiceDueDateWrapper} mb-3`}>
                                            <label htmlFor="companyInvoiceDueDate" className="form-label">Due Date</label>
                                            <div className={`d-flex align-content-center`}>
                                                <input type="text" className="form-control" id="companyInvoiceDueDate" aria-describedby="emailHelp" />
                                                <i><FontAwesomeIcon icon={faCalendar} /></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <hr />
                            <div className="row"></div>
                            <hr />
                            <div className="companyInvoiceTotalWrapper">
                                <div className="row">
                                    <div className="col md-6">
                                        <div className="mb-3">
                                            <label htmlFor="exampleFormControlTextarea1" className="form-label">Customer Notes</label>
                                            <textarea className="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                                        </div>
                                    </div>
                                    <div className="col md-6"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    )
}