import Head from 'next/head';
import Image from 'next/image';
import RadioButton from '../components/radioButton';
import styles from "../styles/newInvoice.module.scss"
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faSearch, faGear, faCalendar } from '@fortawesome/free-solid-svg-icons';
import { useState } from 'react';
export default function Newinvoice({ navExpandedState }) {
    const [taxValueSelected, settaxValueSelected] = useState(false);
    const handleTDSChange = () => {
        settaxValueSelected('tds');
    };

    const handleTCSChange = () => {
        settaxValueSelected('tcs');
    };
    return (
        <div className={styles.container}>
            <Head>
                <title>Groovy Invoice - New Invoice</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${navExpandedState ? styles.expanded : " "}`}>
                <h2 className={`${styles.title}`}>
                    New Invoice
                </h2>
                <div className="container-fluid">
                    <div className={`${styles.card} card`}>
                        <div className="card-body">
                            <h4 className={`${styles.cardTitle} card-title`}>Customer & Invoice Details</h4>
                            <hr />
                            <div className={`${styles.mainWrapper}`}>
                                <div className="row">
                                    <div className="col-md-4 ">
                                        <div className={`${styles.companyNameWrapper} form-group`}>
                                            <label htmlFor="companyName" className="form-label control-label">Comapny Name<span className={`${styles.green}`}>*</span></label>
                                            <div className="d-flex">
                                                <select className={`${styles.companyNameSelect} form-select`}>
                                                    <option defaultValue>Select Customer</option>
                                                    <option value="1">One</option>
                                                    <option value="2">Two</option>
                                                    <option value="3">Three</option>
                                                </select>
                                                <button className={`${styles.companySearchbutton} btn`}><i><FontAwesomeIcon icon={faSearch} /></i></button>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="col-sm-3">
                                        <div className={`${styles.companyInvoiceNumberWrapper} mb-3`}>
                                            <label htmlFor="companyInvoiceNumber" className="form-label">Invoice#<span className={`${styles.green}`}>*</span></label>
                                            <div className={`d-flex align-content-center`}>
                                                <input type="text" className="form-control" id="companyInvoiceNumber" aria-describedby="emailHelp" />
                                                <i><FontAwesomeIcon icon={faGear} /></i>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="col-sm-3">
                                        <div className={`${styles.companyOrderNumberWrapper} mb-3`}>
                                            <label htmlFor="companyOrderNumber" className="form-label">Order Number</label>
                                            <div className={`d-flex align-content-center`}>
                                                <input type="text" className="form-control" id="companyOrderNumber" aria-describedby="emailHelp" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="row">
                                    <div className="col-md-2">
                                        <div className={`${styles.companyInvoiceDateWrapper} mb-3`}>
                                            <label htmlFor="companyInvoiceDate" className="form-label">Invoice Date<span className={`${styles.green}`}>*</span></label>
                                            <div className={`d-flex align-content-center`}>
                                                <input type="text" className="form-control" id="companyInvoiceDate" aria-describedby="emailHelp" />
                                                <i><FontAwesomeIcon icon={faCalendar} /></i>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="col-md-2">
                                        <div className={`${styles.companyInvoicetermsWrapper} mb-3`}>
                                            <label htmlFor="companyInvoiceterms" className="form-label">Terms</label>
                                            <div className={`d-flex align-content-center`}>
                                                <input type="text" className="form-control" id="companyInvoiceterms" aria-describedby="emailHelp" />
                                            </div>
                                        </div>
                                    </div>
                                    <div className="col-md-2">
                                        <div className={`${styles.companyInvoiceDueDateWrapper} mb-3`}>
                                            <label htmlFor="companyInvoiceDueDate" className="form-label">Due Date</label>
                                            <div className={`d-flex align-content-center`}>
                                                <input type="text" className="form-control" id="companyInvoiceDueDate" aria-describedby="emailHelp" />
                                                <i><FontAwesomeIcon icon={faCalendar} /></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <hr />
                            <div className="row"></div>
                            <hr />
                            <div className={`${styles.companyInvoiceBottomWrapper}`}>
                                <div className="row justify-content-left">
                                    <div className="col-md-5">
                                        <div className="mb-3">
                                            <label htmlFor="companyInvoiceCustomerNotes" className="form-label">Customer Notes</label>
                                            <textarea className="form-control" placeholder='Enter note' id="companyInvoiceCustomerNotes" rows="7"></textarea>
                                        </div>
                                    </div>
                                    <div className="col-md-4">
                                        <div className={`${styles.card} card justify-content-between`} >
                                            <div className="card-body">
                                                <div className="d-flex justify-content-between">
                                                    <div className={`${styles.subtotalLabel}`}>Sub Total</div>
                                                    <div className={`${styles.subtotalresult}`}>Rs. 18.00</div>
                                                </div>
                                                <div className={`${styles.comapnyInvoiceTaxOptionWrapper} d-flex align-content-center`}>
                                                    <span className={`${styles.taxTDSRadioButtonWrapper} d-flex align-items-center`}>
                                                        <RadioButton
                                                            label="TDS"
                                                            value={taxValueSelected === 'tds'}
                                                            onChange={handleTDSChange}
                                                        />
                                                    </span>
                                                    <span className={`${styles.taxTCSRadioButtonWrapper} d-flex align-items-center`}>
                                                        <RadioButton
                                                            label="TCS"
                                                            value={taxValueSelected === 'tcs'}
                                                            onChange={handleTCSChange}
                                                        />
                                                    </span>
                                                    <span className={`${styles.taxTypeSelectWrapper}`}>
                                                        <select className={`${styles.taxTypeSelect} form-select`}>
                                                            <option defaultValue>Select Tax</option>
                                                            <option value="1">One</option>
                                                            <option value="2">Two</option>
                                                        </select>
                                                    </span>
                                                    <span className={`${styles.totalCalculatedTax} d-flex`}>
                                                        <span>-0.00</span>
                                                    </span>
                                                </div>
                                                <div className={`${styles.companyInvoiceAdjustmentWrapper}`}>

                                                </div>
                                                <hr />

                                            </div>
                                        </div>
                                    </div>
                                    <div className="col-md-8">
                                        <div className={`${styles.companyInvoiceTermsnConditionsWrapper} mb-3`}>
                                            <label htmlFor="companyInvoiceTerms&Conditions" className="form-label">Terms & Conditions</label>
                                            <textarea className="form-control" placeholder='Enter the terms and conditions of your business to be displayed in your transaction' id="companyInvoiceTerms&Conditions" rows="7"></textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    )
}