import Head from 'next/head';
import styles from '../styles/payment.module.scss';

export default function Reports({ navExpandedState }) {
    return (<>
        <div className={styles.container}>
            <Head>
                <title>Groovy Invoice</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${navExpandedState ? styles.expanded : " "}`}>
                <div className="container-fluid">
                    <h2 className={`${styles.title}`}>
                        Payment for #VS2022/09-01
                    </h2>
                    <div className={`${styles.card} card`}>
                        <div className={`${styles.companyInvoiceCustomerNameWrapper} mb-3 row`}>
                            <div className="col-10">
                                <label className={`${styles.companyInvoiceCustomerNameLabel}`}>Customer Name<span className={`${styles.green}`}>*</span></label>
                            </div>
                            <div className="col-12 col-lg-5 mt-2">
                                <input type="email" className="form-control" id="companyInvoiceCustomerName" placeholder='Company Email' />
                            </div>
                        </div>
                    </div>
                </div>

            </main>
        </div>
    </>)
}