import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/viewInvoice.module.scss';
import FaPen from '../assets/icons/faPen.svg';
import FaMail from '../assets/icons/faEnvelopeGreen.svg';
import FaShare from '../assets/icons/faShare.svg';
import FaBell from '../assets/icons/faBell.svg';
import FaPDF from '../assets/icons/faPDF.svg';
import FaRupee from '../assets/icons/faRupee.svg';

export default function viewInvoice({ navExpandedState }) {
    return (<>
        <div className={styles.container}>
            <Head>
                <title>Groovy Invoice</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${navExpandedState ? styles.expanded : " "}`}>
                <div className="container-fluid">
                    <div className={`${styles.comapnyInvoiceViewInvoiceHeadWrapper} row`}>
                        <div className={`${styles.comapnyInvoiceViewInvoiceMainHeading} col-9 col-md-10 col-lg-5`}>Maximus Tempor <span className={`${styles.comapnyInvoiceViewInvoiceSubHeading}`}>#2022/09-04</span></div>
                        <div className={`${styles.companyInvoiceViewInvoiceActionBarWrapper} col-12 col-md-11`}>
                            <nav className={`${styles.companyInvoiceViewInvoiceActionBar} navbar navbar-expand-lg`}>
                                <div className="container-fluid">
                                    <span className={`${styles.companyInvoiceViewInvoiceActionBarAction} navbar-brand`}>Action</span>
                                    <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                                        <span className="navbar-toggler-icon"></span>
                                    </button>
                                    <div className={`${styles.companyInvoiceViewInvoiceActionBarCollapse} collapse navbar-collapse`} id="navbarNavDropdown">
                                        <ul className="navbar-nav">
                                            <li className={`${styles.companyInvoiceViewInvoiceActionBarActionItem} nav-item`}>
                                                <span className={`${styles.companyInvoiceViewInvoiceActionBarActionItemText} nav-link`}> <span className={`${styles.companyInvoiceViewInvoiceActionBarActionItemIcon}`}><FaPen /></span> Edit</span>
                                            </li>
                                            <li className={`${styles.companyInvoiceViewInvoiceActionBarActionItem} nav-item dropdown`}>
                                                <a className={`${styles.companyInvoiceViewInvoiceActionBarActionItemText} nav-link dropdown-toggle`} href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                                    <span className={`${styles.companyInvoiceViewInvoiceActionBarActionItemIcon}`}><FaMail /></span>  Mail / SMS
                                                </a>
                                                <ul className="dropdown-menu">
                                                    <li><span className="dropdown-item">Action</span></li>
                                                    <li><span className="dropdown-item">Another action</span></li>
                                                    <li><span className="dropdown-item">Something else here</span></li>
                                                </ul>
                                            </li>
                                            <li className={`${styles.companyInvoiceViewInvoiceActionBarActionItem} nav-item`}>
                                                <span className={`${styles.companyInvoiceViewInvoiceActionBarActionItemText} nav-link`}><span className={`${styles.companyInvoiceViewInvoiceActionBarActionItemIcon}`}><FaShare /></span>Share</span>
                                            </li>
                                            <li className={`${styles.companyInvoiceViewInvoiceActionBarActionItem} nav-item dropdown`}>
                                                <a className={`${styles.companyInvoiceViewInvoiceActionBarActionItemText} nav-link dropdown-toggle`} href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                                    <span className={`${styles.companyInvoiceViewInvoiceActionBarActionItemIcon}`}><FaBell /></span>  Reminders
                                                </a>
                                                <ul className="dropdown-menu">
                                                    <li><span className="dropdown-item">Action</span></li>
                                                    <li><span className="dropdown-item">Another action</span></li>
                                                </ul>
                                            </li>
                                            <li className={`${styles.companyInvoiceViewInvoiceActionBarActionItem} nav-item dropdown`}>
                                                <a className={`${styles.companyInvoiceViewInvoiceActionBarActionItemText} nav-link dropdown-toggle`} href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                                    <span className={`${styles.companyInvoiceViewInvoiceActionBarActionItemIcon}`}><FaPDF /></span>  PDF / Print
                                                </a>
                                                <ul className="dropdown-menu">
                                                    <li><span className="dropdown-item">Action</span></li>
                                                    <li><span className="dropdown-item">Another action</span></li>
                                                </ul>
                                            </li>
                                            <li className={`${styles.companyInvoiceViewInvoiceActionBarActionItem} nav-item`}>
                                                <span className={`${styles.companyInvoiceViewInvoiceActionBarActionItemText} nav-link`}><span className={`${styles.companyInvoiceViewInvoiceActionBarActionItemIcon}`}><FaRupee /></span>Record Payment</span>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </>)
}